### ISSUE TITLE
TypeError: can't concat bytes to str - lib/python3.4/site-packages/redisboard/admin.py", line 44, in slowlog

### ISSUE THREAD

**Issue by foxmask** [ionelmc/django-redisboard#18]
this error occurs when I access to the admin ; here is the full log 

```
2015-08-25 10:23:53,698 ERROR base 12916 Internal Server Error: /admin/redisboard/redisserver/
Traceback (most recent call last):
  File "/home/foxmask/lib/python3.4/site-packages/django/db/models/options.py", line 552, in get_field
    return self.fields_map[field_name]
KeyError: 'slowlog'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/foxmask/lib/python3.4/site-packages/django/contrib/admin/utils.py", line 266, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/home/foxmask/lib/python3.4/site-packages/django/contrib/admin/utils.py", line 297, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/home/foxmask/lib/python3.4/site-packages/django/db/models/options.py", line 554, in get_field
    raise FieldDoesNotExist('%s has no field named %r' % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: RedisServer has no field named 'slowlog'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/foxmask/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/foxmask/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/foxmask/lib/python3.4/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/home/foxmask/lib/python3.4/site-packages/django/template/base.py", line 1271, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/home/foxmask/lib/python3.4/site-packages/django/contrib/admin/templatetags/admin_list.py", line 320, in result_list
    'results': list(results(cl))}
  File "/home/foxmask/lib/python3.4/site-packages/django/contrib/admin/templatetags/admin_list.py", line 296, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/foxmask/lib/python3.4/site-packages/django/contrib/admin/templatetags/admin_list.py", line 287, in __init__
    super(ResultList, self).__init__(*items)
  File "/home/foxmask/lib/python3.4/site-packages/django/contrib/admin/templatetags/admin_list.py", line 199, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/foxmask/lib/python3.4/site-packages/django/contrib/admin/utils.py", line 278, in lookup_field
    value = attr(obj)
  File "/home/foxmask/lib/python3.4/site-packages/redisboard/admin.py", line 44, in slowlog
    command = command[:252] + '...'
TypeError: can't concat bytes to str
```

I put a logger 2 lines before that displays this 

```
2015-08-25 10:23:53,343 CRITICAL admin 12916 b'MULTI'
2015-08-25 10:23:53,343 CRITICAL admin 12916 b'RPOP options'
2015-08-25 10:23:53,343 CRITICAL admin 12916 b'EXPIRE l:b:p 60'
2015-08-25 10:23:53,344 CRITICAL admin 12916 b'LPUSH counters-0 {"body": "gAJ9cQEoVQdleHBpcmVzcQJVGjIwMTUtMDgtMjVUMDY6MTc6MjAuNDg4MDQ1cQNVA3V0Y3EEiFUEYXJnc3EFXXEGVQVjaG9yZHEHTlUJY2FsbGJhY2tzcQ... (511 more bytes)'
2015-08-25 10:23:53,344 CRITICAL admin 12916 b'MULTI'
2015-08-25 10:23:53,344 CRITICAL admin 12916 b'BRPOP search sourcemaps cleanup email triggers-0 events default update auth alerts counters-0 options search\x06\x163 sourcemaps\x06\x163 cleanup\x06\x163 email\x06\x163 triggers-0\x06\x163 events\x06\x163 default\x06\x163 update\x06\x163 auth\x06\x163 alerts\x06\x163 counters-0\x06\x163 options\x06\x163 search\x06\x166 sourcemaps\x06\x166 cleanup\x06\x166 email\x06\x166 triggers-0\x06\x166 events\x06\x166 ... (19 more arguments)'
```

**Comment by ionelmc** [comment]
What's your redis client version? Can you try with latest?

**Comment by foxmask** [comment]
i tried with 1.2.0 and 1.2.2

**Comment by ionelmc** [comment]
Those releases don't exist. Eg: https://pypi.python.org/pypi/redis/1.2.2

Try using `pip freeze | grep redis`.

**Comment by foxmask** [comment]
yes sorry i meant 1.2.0 and 1.2.1

**Comment by ionelmc** [comment]
Looks like there's some need of bytes literals over there in admin.py (`b'...'`) ...

**Comment by ionelmc** [comment]
Interested in making some contributions? :grimacing:

**Comment by foxmask** [comment]
hehe :) i will see if i'm able to try something - may be it's related to the fact that i only use python 3.4

**Comment by foxmask** [comment]
on my dev environment I dont meet this error ... I can see the contain of slowlog without any error .

**Comment by ionelmc** [comment]
I will take a look later. That line doesn't have test coverage anyway ...

**Comment by foxmask** [comment]
I fixed it like this 

            if len(command) > 255:
                command = str(command[:252]) + '...'

instead of 

            if len(command) > 255:
                command = command[:252] + '...'

**Comment by foxmask** [comment]
Off Topic :

here https://docs.djangoproject.com/en/1.8/topics/cache/#cache-versioning we can set a version > 1 but I dont find them in the redisboard. Is it possible to spot them ?

**Comment by gabn88** [comment]
This is also fixed :)

**Comment by foxmask** [comment]
I'll have a look on my prod env this morning and keep you posted

**Comment by foxmask** [comment]
version 3.0.2 + django 1.11 ok
