### ISSUE TITLE
Specifying a password for a non-password protected database breaks django-redisboard completely

### ISSUE THREAD

**Issue by gabn88** [ionelmc/django-redisboard#21]
Log trace:

    raise FieldDoesNotExist('%s has no field named %r' % (self.object_name, name))
django.db.models.fields.FieldDoesNotExist: RedisServer has no field named 'cpu_utilization'

&

  File "/home/gabn88/.local/lib/python3.4/site-packages/redisboard/admin.py", line 95, in cpu_utilization
    data = dict((k, stats['details'][k]) for k in data)
  File "/home/gabn88/.local/lib/python3.4/site-packages/redisboard/admin.py", line 95, in <genexpr>
    data = dict((k, stats['details'][k]) for k in data)
KeyError: 'used_cpu_sys'

**Comment by ionelmc** [comment]
What redis server version do you have? What redis client library version?

**Comment by gabn88** [comment]
Thanks for you response.

It was my config (using redis 3.0.5 and redis-py 2.10.3), I had set port 0, and used sockets instead. However, my cron script was starting every 5 minutes a new redis-server instances (which it did not do before I had put port 0). So there were 66 redis instances on the socket, which redisboard did not like.

However, with the port 0 option the error persists. It seems redisboard it not usable with socket only configurations of redis :(

**Comment by ionelmc** [comment]
So you had instances with a port set? Can you explain again what is the actual bug in redisboard?

**Comment by gabn88** [comment]
The bug is that setting port 0 in the redis.conf gives a 500 error on /admin/redisboard/redisserver/.

Full error trace log:

Internal Server Error: /admin/redisboard/redisserver/ Traceback (most recent call last):
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/contrib/admin/utils.py", line 264, in lookup_field
    f = opts.get_field(name)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/db/models/options.py", line 398, in get_field
    raise FieldDoesNotExist('%s has no field named %r' % (self.object_name, name))
django.db.models.fields.FieldDoesNotExist: RedisServer has no field named 'cpu_utilization'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/response.py", line 80, in rendered_content
    content = template.render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 148, in render
    return self._render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/template/base.py", line 1207, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/contrib/admin/templatetags/admin_list.py", line 316, in result_list
    'results': list(results(cl))}
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/contrib/admin/templatetags/admin_list.py", line 292, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/contrib/admin/templatetags/admin_list.py", line 283, in __init__
    super(ResultList, self).__init__(*items)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/contrib/admin/templatetags/admin_list.py", line 198, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "django/lib/python3.4/Django-1.7.10-py3.4.egg/django/contrib/admin/utils.py", line 276, in lookup_field
    value = attr(obj)
  File "/home/.local/lib/python3.4/site-packages/redisboard/admin.py", line 95, in cpu_utilization
    data = dict((k, stats['details'][k]) for k in data)
  File "/home/.local/lib/python3.4/site-packages/redisboard/admin.py", line 95, in <genexpr>
    data = dict((k, stats['details'][k]) for k in data)
KeyError: 'used_cpu_sys'

**Comment by gabn88** [comment]
Thank you for the quick response.

I have upgraded django-redisboard via pip (to 2.0.0) and the issue still persists.

I think I get the issue because I have no tcp connection to my redis database, only a socket!

**Comment by ionelmc** [comment]
Not sure now. Can you provide a traceback with new version?

On Sunday, 15 November 2015, gabn88 <notifications@github.com> wrote:

> Thank you for the quick response.
>
> I have upgraded django-redisboard via pip (to 2.0.0) and the issue still
> persists.
>
> I think I get the issue because I have no tcp connection to my redis
> database, only a socket!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ionelmc/django-redisboard/issues/21#issuecomment-156813504>
> .
>


-- 

Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by gabn88** [comment]
Argh, sorry! I forgot to restart my server! It works! Thank you very much!
