### ISSUE TITLE
Django 1.9 compatiblity

### ISSUE THREAD

**Issue by Uninen** [ionelmc/django-redisboard#23]
Django 1.9rc1 gives following traceback:

"""
Traceback (most recent call last):
  File "/home/uninen/projects/djuninennet/djuninennet/manage.py", line 15, in <module>
    django.setup()
  File "/home/uninen/.virtualenvs/djuninennet/local/lib/python2.7/site-packages/django/**init**.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/uninen/.virtualenvs/djuninennet/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/uninen/.virtualenvs/djuninennet/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/home/uninen/.virtualenvs/djuninennet/local/lib/python2.7/site-packages/redisboard/models.py", line 11, in <module>
    from django.utils.datastructures import SortedDict
ImportError: cannot import name SortedDict
"""

It seems SortedDict should be replaced with OrderedDict: https://docs.djangoproject.com/en/1.8/ref/utils/#module-django.utils.datastructures

**Comment by ionelmc** [comment]
PR please? :grimacing:

**Comment by ionelmc** [comment]
Support was dropped. 1.9 is unmaintained anyway.
