### ISSUE TITLE
b'none' KeyError in Inspect view

### ISSUE THREAD

**Issue by eriktelepovsky** [ionelmc/django-redisboard#35]
```
KeyError at /sk/admin/redisboard/redisserver/1/inspect/
b'none'

Traceback (most recent call last):
  File "/Users/erik/env/swida/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/erik/env/swida/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/erik/env/swida/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/erik/src/django/swida/source/redisboard/admin.py", line 130, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/erik/env/swida/lib/python3.5/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/erik/env/swida/lib/python3.5/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/erik/env/swida/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/Users/erik/src/django/swida/source/redisboard/admin.py", line 145, in inspect_view
    return inspect(request, server)
  File "/Users/erik/src/django/swida/source/redisboard/views.py", line 232, in inspect
    key_details = _get_key_details(conn, db, key, page)
  File "/Users/erik/src/django/swida/source/redisboard/views.py", line 106, in _get_key_details
    details = _get_key_info(conn, key)
  File "/Users/erik/src/django/swida/source/redisboard/views.py", line 54, in _get_key_info
    LENGTH_GETTERS[obj_type](pipe, key)
KeyError: b'none'
```

**Comment by gilav** [comment]
Hello

Had the same problem.  
Fix it by converting the 'key' request value which is of type str into bytes value. Before calling _get_key_details() at line 232:

        if 'key' in request.GET:
            key = request.GET['key']
            db = request.GET.get('db', 0)
            page = request.GET.get('page', 1)
            if isinstance(key, str) and key.startswith("b'") and key.endswith("'"):
                key =str.encode(key[2:-1])
            key_details = _get_key_details(conn, db, key, page)

**Comment by eriktelepovsky** [comment]
Hi @gilav 

Thank you for your answer. Can you create a pull request if your solution works generally? Thanks.

**Comment by gilav** [comment]
Hello

I have created a pull request for this, also for the other issue I had (#36). 
Hope I did it well: never made pull request before ...

(also hope fix is ok: I am not a django expert)

Best regards

Gilles

**Comment by ionelmc** [comment]
This should be fixed now.
