### ISSUE TITLE
Django 3.0 compatibility

### ISSUE THREAD

**Issue by supermanzer** [ionelmc/django-redisboard#42]
**Operating System**:
 - Ubuntu 16.04 LTS
 - Application running in Docker image `python:3.7`

**Software/Package Versions**
 - Python=3.7
 - Django=3.0.0
 - django-redis=4.10.0
 - django-redisboard=4.0.0

**Issue**:
  Attempting to spin up Django project after updating to Django 3.0.0 results in the following module loading failure.  Steps taken were as follows:
 1. `pip install --upgrade django`
 2. `python manage.py runserver`

This triggers the following exception with traceback:
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/redisboard/models.py", line 17, in <module>
    from django.utils.datastructures import SortedDict as OrderedDict
ImportError: cannot import name 'SortedDict' from 'django.utils.datastructures' (/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/redisboard/models.py", line 19, in <module>
    from django.utils.datastructures import OrderedDict
ImportError: cannot import name 'OrderedDict' from 'django.utils.datastructures' (/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py)
```

**Comment by ionelmc** [comment]
Released 4.1.0 just now.
