### ISSUE TITLE
No module named 'attr'

### ISSUE THREAD

**Issue by basitiyidir** [ionelmc/django-redisboard#49]
**Operating System:**

Application running in Docker image python:3.10.2-slim

**Software/Package Versions**

Python=3.10
Django=4.0.5
django-redisboard==8.3.0
redis==4.3.3

**Issue:**

```
Traceback (most recent call last):
  File "/code/./manage.py", line 21, in <module>
    main()
  File "/code/./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.10/site-packages/django/apps/config.py", line 304, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/redisboard/models.py", line 10, in <module>
    from attr import Factory
ModuleNotFoundError: No module named 'attr'
```

**Comment by ionelmc** [comment]
Released 8.3.1.
